web:
  build: ./server
  volumes:
    - ./server:/home/src/server:rw
    # - ./../frontend:/home/public
  ports:
    - "8080:8080"
  environment:
    NODE_ENV: development
  command: npm start
  container_name: radumicu.com-dev
